apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argo-cd
  # finalizers:
  # - resources-finalizer.argo-cd.argoproj.io
spec:
  destination:
    namespace: helm-guestbook
    server: {{ .Values.spec.destination.server }}
  project: test
  source:
    helm:
      parameters:
      - name: ingress.enabled
        value: "true"
      # - name: ingress.hosts[0]
      #   value: helm-guestbook.dev.local
      valueFiles:
      - values.yaml
    path: helm-guestbook
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: {{ .Values.spec.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.spec.syncPolicy.automated.selfHeal }}