apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-hooks
  namespace: argo-cd
  # finalizers:
  # - resources-finalizer.argo-cd.argoproj.io
spec:
  destination:
    namespace: helm-hooks
    server: {{ .Values.spec.destination.server }}
  project: test
  source:
    path: helm-hooks
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: {{ .Values.spec.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.spec.syncPolicy.automated.selfHeal }}
