apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-guestbook
  namespace: argo-apps-test-2
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kustomize-guestbook
    server: {{ .Values.spec.destination.server }}
  project: test
  source:
    path: kustomize-guestbook
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
