apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-waves
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argo-cd.argoproj.io
spec:
  destination:
    namespace: sync-waves
    server: {{ .Values.spec.destination.server }}
  project: test
  source:
    path: sync-waves
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: {{ .Values.spec.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.spec.syncPolicy.automated.selfHeal }}