spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/biyanisuraj/argocd-example-apps
    targetRevision: 94ad32f4ea26798997774ffc3e20fbfa8e0d8c21
  syncPolicy:
    automated:
      prune: true
      selfHeal: true