spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/biyanisuraj/argocd-example-apps
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true